pcm.teletool_inferno {
    type inferno
    NAME "TeleTool"
    SAMPLE_RATE "48000"
    PROCESS_ID "1"
    ALT_PORT "6000"
    RX_CHANNELS "0"
    TX_CHANNELS "2"
    CLOCK_PATH "/run/teletool-inferno/usrvclock.sock"
    RX_LATENCY_NS "10000000"
    TX_LATENCY_NS "10000000"
    hint {
        show on
        description "TeleTool Inferno network output"
    }
}
